### Load the Datasets

In [72]:
import numpy as np 
import pandas as pd  
import matplotlib.pyplot as plt  
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")


In [73]:
df1=pd.read_csv(r"C:\Users\devav\Downloads\reveiw data\data1.csv")
df2=pd.read_csv(r"C:\Users\devav\Downloads\reveiw data\data.csv")
df3=pd.read_csv(r"C:\Users\devav\Downloads\reveiw data\data3.csv")

### Check the Datasets

In [74]:
df1.head(5)

Reviewer Name               Review Title  \
0            Kamal Suresh               Nice product   
1       Flipkart Customer     Don't waste your money   
2  A. S. Raja Srinivasan   Did not meet expectations   
3     Suresh Narayanasamy                       Fair   
4               ASHIK P A                Over priced   

               Place of Review  Up Votes  Down Votes     Month  \
0   Certified Buyer, Chirakkal     889.0        64.0  Feb 2021   
1   Certified Buyer, Hyderabad     109.0         6.0  Feb 2021   
2  Certified Buyer, Dharmapuri      42.0         3.0  Apr 2021   
3     Certified Buyer, Chennai      25.0         1.0       NaN   
4                          NaN     147.0        24.0  Apr 2016   

                                         Review text  Ratings  
0  Nice product, good quality, but price is now r...        4  
1  They didn't supplied Yonex Mavis 350. Outside ...        1  
2  Worst product. Damaged shuttlecocks packed in ...        1  
3  Quite O. K. , but nowadays  the quality of the...        3  
4  Over pricedJust â?¹620 ..from retailer.I didn'...        1

In [75]:
df2.head(5)

Reviewer_Name  Reviewer_Rating           Review_Title  \
0     Sumit  Kumar              5.0              Wonderful   
1  BHARAT GALAGALI              5.0  Mind-blowing purchase   
2  Paramjeet Singh              5.0                Awesome   
3  Virendra  Kumar              5.0          Great product   
4    jyoti solanki              5.0    Best in the market!   

                                         Review_Text  \
0  I think In this price category it's best dosa ...   
1                   perfect tawa for Dosa..READ MORE   
2  Excellent tawa. Made Paneer Tikka on first day...   
3                            Nice 🙂 productREAD MORE   
4             Delivery man is also good....READ MORE   

                          Place_of_Review   Date_of_Review  Up_Votes  \
0             Certified Buyer, Lakhisarai     Sumit  Kumar       211   
1                 Certified Buyer, Hunsur  BHARAT GALAGALI       107   
2           Certified Buyer, Rampura Phul  Paramjeet Singh        59   
3  Certified Buyer, Chengalpattu District  Virendra  Kumar        77   
4                 Certified Buyer, Mumbai    jyoti solanki        53   

   Down_Votes  
0          39  
1          17  
2           8  
3          12  
4           7

In [76]:
df3.head(5)

reviewer_name  reviewer_rating        review_title  \
0   Subhro  Banerjee                5   Worth every penny   
1  Shiv chandra  Jha                5       Great product   
2  Flipkart Customer                5  Highly recommended   
3              DTH Y                4           Very Good   
4    Bhavesh Godhani                5      Classy product   

                                         review_text  \
0  Great product 🤗 with great deals 😍😍 Tata Tea G...   
1  Very nice and super qwality tea taste are grea...   
2  Great test great quality great price point tim...   
3                                    Nice 😊READ MORE   
4               Very Good Tata tea product.READ MORE   

                   place_of_review     Date_of_review  up_votes  Down_votes  
0     Certified Buyer, Budge Budge   Subhro  Banerjee       236          59  
1         Certified Buyer, Saharsa  Shiv chandra  Jha       225          79  
2  Certified Buyer, Sri Ganganagar  Flipkart Customer        89          27  
3         Certified Buyer, Phaltan              DTH Y        30           6  
4       Certified Buyer, Ahmedabad    Bhavesh Godhani        69          22

In [77]:
print(df1.shape,df2.shape,df3.shape)

(8518, 8) (2531, 8) (9170, 8)


In [78]:
print(df1.info)

<bound method DataFrame.info of                Reviewer Name               Review Title  \
0               Kamal Suresh               Nice product   
1          Flipkart Customer     Don't waste your money   
2     A. S. Raja Srinivasan   Did not meet expectations   
3        Suresh Narayanasamy                       Fair   
4                  ASHIK P A                Over priced   
...                      ...                        ...   
8513                     NaN                        NaN   
8514                     NaN                        NaN   
8515                     NaN                        NaN   
8516                     NaN                        NaN   
8517                     NaN                        NaN   

                  Place of Review  Up Votes  Down Votes     Month  \
0      Certified Buyer, Chirakkal     889.0        64.0  Feb 2021   
1      Certified Buyer, Hyderabad     109.0         6.0  Feb 2021   
2     Certified Buyer, Dharmapuri      42.0         

In [79]:
print(df2.info)


<bound method DataFrame.info of           Reviewer_Name  Reviewer_Rating           Review_Title  \
0          Sumit  Kumar              5.0              Wonderful   
1       BHARAT GALAGALI              5.0  Mind-blowing purchase   
2       Paramjeet Singh              5.0                Awesome   
3       Virendra  Kumar              5.0          Great product   
4         jyoti solanki              5.0    Best in the market!   
...                 ...              ...                    ...   
2526  Sandeep Mohapatra              3.0                   Fair   
2527        Vakul  Rana              4.0   Good quality product   
2528  Somraj  Dhungana               4.0            Really Nice   
2529       Veeranna N C              3.0                   Good   
2530  Flipkart Customer              3.0              Just okay   

                                            Review_Text  \
0     I think In this price category it's best dosa ...   
1                      perfect tawa for Dosa.

In [80]:
print(df3.info)

<bound method DataFrame.info of           reviewer_name  reviewer_rating        review_title  \
0      Subhro  Banerjee                5   Worth every penny   
1     Shiv chandra  Jha                5       Great product   
2     Flipkart Customer                5  Highly recommended   
3                 DTH Y                4           Very Good   
4       Bhavesh Godhani                5      Classy product   
...                 ...              ...                 ...   
9165       Omm Prakash                 5      Simply awesome   
9166           Ritu Raj                4         Good choice   
9167         Arun Saini                1    Terrible product   
9168      Amitabh Shahi                5           Just wow!   
9169    Rohan  Bhowmik                 5      Simply awesome   

                                            review_text  \
0     Great product 🤗 with great deals 😍😍 Tata Tea G...   
1     Very nice and super qwality tea taste are grea...   
2     Great test great

In [81]:
print(df1.dtypes)
print(df2.dtypes)
print(df3.dtypes)

Reviewer Name       object
Review Title        object
Place of Review     object
Up Votes           float64
Down Votes         float64
Month               object
Review text         object
Ratings              int64
dtype: object
Reviewer_Name       object
Reviewer_Rating    float64
Review_Title        object
Review_Text         object
Place_of_Review     object
Date_of_Review      object
Up_Votes             int64
Down_Votes           int64
dtype: object
reviewer_name      object
reviewer_rating     int64
review_title       object
review_text        object
place_of_review    object
Date_of_review     object
up_votes            int64
Down_votes          int64
dtype: object


In [82]:
print(df1.columns)
print(df2.columns)
print(df3.columns)

Index(['Reviewer Name', 'Review Title', 'Place of Review', 'Up Votes',
       'Down Votes', 'Month', 'Review text', 'Ratings'],
      dtype='object')
Index(['Reviewer_Name', 'Reviewer_Rating', 'Review_Title', 'Review_Text',
       'Place_of_Review', 'Date_of_Review', 'Up_Votes', 'Down_Votes'],
      dtype='object')
Index(['reviewer_name', 'reviewer_rating', 'review_title', 'review_text',
       'place_of_review', 'Date_of_review', 'up_votes', 'Down_votes'],
      dtype='object')


### Extract the columns

In [83]:
df1=df1[['Review Title','Review text','Ratings']]
df2=df2[['Review_Title','Review_Text','Reviewer_Rating']]
df3=df3[['review_title','review_text','reviewer_rating']]

In [84]:
df1 = df1.rename(columns={
    'Review Title': 'review_title',
    'Review text': 'review_text',
    'Ratings': 'rating'
})

df2 = df2.rename(columns={
    'Review_Title': 'review_title',
    'Review_Text': 'review_text',
    'Reviewer_Rating': 'rating'
})

df3 = df3.rename(columns={
    'reviewer_rating': 'rating'
})

### Combine the three dataframe

In [85]:
df = pd.concat([df1, df2, df3], ignore_index=True)


###  Details of new data frame

In [86]:
df.head()

review_title  \
0               Nice product   
1     Don't waste your money   
2  Did not meet expectations   
3                       Fair   
4                Over priced   

                                         review_text  rating  
0  Nice product, good quality, but price is now r...     4.0  
1  They didn't supplied Yonex Mavis 350. Outside ...     1.0  
2  Worst product. Damaged shuttlecocks packed in ...     1.0  
3  Quite O. K. , but nowadays  the quality of the...     3.0  
4  Over pricedJust â?¹620 ..from retailer.I didn'...     1.0

In [87]:
df.shape

(20219, 3)

###  Check the Duplicates

In [88]:
df.duplicated().sum()

11536

In [89]:
df1.duplicated().sum()

1498

In [90]:
df2.duplicated().sum()

602

In [91]:
df3.duplicated().sum()

9160

In [92]:
df.duplicated().sum()

11536

### Drop the duplicates

In [93]:
df=df.drop_duplicates()

In [94]:
df.head()

review_title  \
0               Nice product   
1     Don't waste your money   
2  Did not meet expectations   
3                       Fair   
4                Over priced   

                                         review_text  rating  
0  Nice product, good quality, but price is now r...     4.0  
1  They didn't supplied Yonex Mavis 350. Outside ...     1.0  
2  Worst product. Damaged shuttlecocks packed in ...     1.0  
3  Quite O. K. , but nowadays  the quality of the...     3.0  
4  Over pricedJust â?¹620 ..from retailer.I didn'...     1.0

In [95]:
df.shape

(8683, 3)

### Handle missing values 

In [96]:
df.isna().sum()

review_title      6
review_text       4
rating          234
dtype: int64

In [97]:
df['review_title'].fillna("No Title", inplace=True)
df = df.dropna(subset=['review_text'])
df['rating'].fillna(df['rating'].median(), inplace=True)


In [98]:
df['review_text'] = df['review_text'].fillna("")


### Create the  sentiment column 

In [99]:
df['sentiment'] = df['rating'].apply(lambda x: 1 if x >= 3 else 0)

### Clean the text

In [100]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))
stop_words.remove("not")
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]
    return " ".join(words)


In [101]:
df['clean_review'] = df['review_text'].apply(clean_text)


In [102]:
df.head()

review_title  \
0               Nice product   
1     Don't waste your money   
2  Did not meet expectations   
3                       Fair   
4                Over priced   

                                         review_text  rating  sentiment  \
0  Nice product, good quality, but price is now r...     4.0          1   
1  They didn't supplied Yonex Mavis 350. Outside ...     1.0          0   
2  Worst product. Damaged shuttlecocks packed in ...     1.0          0   
3  Quite O. K. , but nowadays  the quality of the...     3.0          1   
4  Over pricedJust â?¹620 ..from retailer.I didn'...     1.0          0   

                                        clean_review  
0  nice product good quality price rising bad sig...  
1  didnt supplied yonex mavis outside cover yonex...  
2  worst product damaged shuttlecock packed new b...  
3  quite k nowadays quality cork like year back u...  
4  pricedjust retaileri didnt understand wat adva...

### split the data into  train and test

In [103]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( df['clean_review'], df['sentiment'], test_size=0.2, random_state=42)

### Vectorization (Text to Vectors)

In [104]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train = tfidf.fit_transform(X_train)
X_test = tfidf.transform(X_test)

### LogisticRegression

In [105]:
from sklearn.linear_model import LogisticRegression

lrmodel = LogisticRegression(class_weight='balanced')
lrmodel.fit(X_train, y_train)


LogisticRegression(class_weight='balanced')

### LogisticRegression score 

In [106]:
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix

y_pred = lrmodel.predict(X_test)
lrscore=accuracy_score(y_test, y_pred)
print("Accuracy:",lrscore )
print(classification_report(y_test, y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.8703917050691244
              precision    recall  f1-score   support

           0       0.45      0.74      0.56       193
           1       0.96      0.89      0.92      1543

    accuracy                           0.87      1736
   macro avg       0.71      0.81      0.74      1736
weighted avg       0.91      0.87      0.88      1736

[[ 143   50]
 [ 175 1368]]


###  MultinomialNB(naive_bayes)

In [107]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train, y_train)

y_pred_nb = nb.predict(X_test)
nb_acc=accuracy_score(y_test, y_pred_nb)
print("Naive Bayes Accuracy:",nb_acc )
print(classification_report(y_test, y_pred_nb))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred_nb))


Naive Bayes Accuracy: 0.8980414746543779
              precision    recall  f1-score   support

           0       0.86      0.10      0.18       193
           1       0.90      1.00      0.95      1543

    accuracy                           0.90      1736
   macro avg       0.88      0.55      0.56      1736
weighted avg       0.89      0.90      0.86      1736

[[  19  174]
 [   3 1540]]


### LinearSVC

In [108]:
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix

svm = LinearSVC(class_weight='balanced')
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)
svm_acc=accuracy_score(y_test, y_pred_svm)
print("SVM Accuracy:", svm_acc)
print(classification_report(y_test, y_pred_svm))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))


SVM Accuracy: 0.8796082949308756
              precision    recall  f1-score   support

           0       0.47      0.72      0.57       193
           1       0.96      0.90      0.93      1543

    accuracy                           0.88      1736
   macro avg       0.72      0.81      0.75      1736
weighted avg       0.91      0.88      0.89      1736

[[ 138   55]
 [ 154 1389]]
[[ 138   55]
 [ 154 1389]]


### RandomForestClassifier

In [109]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(class_weight='balanced',n_estimators=200, random_state=42)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
rf_acc= accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy:",rf_acc)
print(classification_report(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))


Random Forest Accuracy: 0.9043778801843319
              precision    recall  f1-score   support

           0       0.58      0.53      0.55       193
           1       0.94      0.95      0.95      1543

    accuracy                           0.90      1736
   macro avg       0.76      0.74      0.75      1736
weighted avg       0.90      0.90      0.90      1736

[[ 102   91]
 [  75 1468]]


### KNeighborsClassifier

In [110]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)
knn_acc=accuracy_score(y_test, y_pred_knn)
print("KNN Accuracy:",knn_acc )
print(classification_report(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))


KNN Accuracy: 0.9066820276497696
              precision    recall  f1-score   support

           0       0.63      0.39      0.48       193
           1       0.93      0.97      0.95      1543

    accuracy                           0.91      1736
   macro avg       0.78      0.68      0.72      1736
weighted avg       0.89      0.91      0.90      1736

[[  76  117]
 [  45 1498]]


**SVM achieved the highest F1-score and recall for reviews. Therefore it was chosen as the final model.**

In [111]:
import joblib

joblib.dump(svm, "sentiment_svm_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")


['tfidf_vectorizer.pkl']